spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/fx_deals
    username: fx_user
    password: fx_password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    com.progresssoft.fxdeals: DEBUG

server:
  port: 8080
